QLDPKS/Models/CategoryRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace QLDPKS.Models
{
    [Table("CategoryRooms")]
    public class CategoryRoom
    {
        [Key]
        [Column("CategoryRoomID")]
        [Required]
        public string CategoryRoomID { get; set; }

        [Column("CategoryRoomName")]
        [Required]
        public string CategoryRoomName { get; set; }

        [Column("NumberOfGuest")]
        [Required]
        public int NumberOfGuest { get; set; }
    }
}

QLDPKS/Areas/Admin/Controllers/CategoryRoomController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Areas.Admin.Controllers
{
    public class CategoryRoomController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public CategoryRoomController()
        {
            _dbContext = new QLKSDatabaseContext();
        }
        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult getCategoryRoom()
        {
            var dataCategoryRoom = _dbContext.CategoryRooms.ToList();

            return Json(new { data = dataCategoryRoom }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Create()
        {
            if (Session != null || (Session)["AdminID"] != null || (Session)["AdminID"].ToString() != "")
            {
                string adminID = Session["AdminID"] as string;
                var dataUser = _dbContext.Admins.Where(x => x.ID == adminID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View();
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult Create(string categoryName, int numberOfGuest)
        {
            CategoryRoom categoryRoom = new CategoryRoom
            {
                CategoryRoomID = RandomString.getRandomString(5),
                CategoryRoomName = categoryName,
                NumberOfGuest = numberOfGuest
            };

            var create = _dbContext.CategoryRooms.Add(categoryRoom);

            if(create != null)
            {
                try
                {
                    _dbContext.SaveChanges();
                    return Json(new { data = "Thêm thành công", status = true }, JsonRequestBehavior.AllowGet);
                }
                catch(DbEntityValidationException e)
                {
                    return Json(new { data = e.Message, status = false }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { data = "Thêm thất bại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Edit(string id)
        {
            if (Session != null || (Session)["AdminID"] != null || (Session)["AdminID"].ToString() != "")
            {
                string adminID = Session["AdminID"] as string;
                var dataUser = _dbContext.Admins.Where(x => x.ID == adminID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            var categoryRoomData = _dbContext.CategoryRooms.Where(x => x.CategoryRoomID == id).FirstOrDefault();
            ViewBag.categoryRoomData = categoryRoomData;
            return View();
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult Edit(string categoryName, int numberOfGuest, string id)
        {
            var check = _dbContext.CategoryRooms.Where(x => x.CategoryRoomID == id).FirstOrDefault();
            if(check != null)
            {
                check.CategoryRoomName = categoryName;
                check.NumberOfGuest = numberOfGuest;
                _dbContext.SaveChanges();

                return Json(new { data = "Cập nhật thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Loại phòng không tồn tại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult Delete(string id)
        {
            var check = _dbContext.CategoryRooms.Where(x => x.CategoryRoomID == id).FirstOrDefault();
            if (check != null)
            {
                _dbContext.CategoryRooms.Remove(check);
                _dbContext.SaveChanges();

                return Json(new { data = "Xoá thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Loại phòng không tồn tại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

QLDPKS/Areas/Admin/Controllers/OrderController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Areas.Admin.Controllers
{
    public class OrderController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public OrderController()
        {
            _dbContext = new QLKSDatabaseContext();
        }

        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult getOrder()
        {
            var data_query = from a in _dbContext.Orders
                             join b in _dbContext.Rooms
                             on a.RoomID equals b.RoomID
                             join c in _dbContext.CategoryRooms
                             on b.CategoryRoomID equals c.CategoryRoomID
                             where a.Status == false
                             select new
                             {
                                 OrderID = a.OrderID,
                                 Email = a.Email,
                                 RoomName = b.RoomName,
                                 CategoryRoomName = c.CategoryRoomName,
                                 ReceivedDate = a.ReceivedDate,
                                 CheckOutDate = a.CheckOutDate,
                                 Amount = a.Amount,
                                 Status = a.Status
                             };
            return Json(new { data = data_query }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult approveOrder(string id)
        {
            var dataOrder = _dbContext.Orders.Where(x => x.OrderID == id).FirstOrDefault();

            if (dataOrder != null)
            {
                string roomID = dataOrder.RoomID;
                var dataRoom = _dbContext.Rooms.Where(x => x.RoomID == roomID).FirstOrDefault();

                dataOrder.Status = true;
                dataRoom.Status = true;

                _dbContext.SaveChanges();

                return Json(new { data = "Duyệt đơn thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Duyệt đơn không thành công", status = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

QLDPKS/Areas/Admin/Controllers/RoomController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Areas.Admin.Controllers
{
    public class RoomController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public RoomController()
        {
            _dbContext = new QLKSDatabaseContext();
        }

        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult getRoom()
        {
            var data_query = from a in _dbContext.Rooms
                             join b in _dbContext.CategoryRooms
                             on a.CategoryRoomID equals b.CategoryRoomID
                             select new
                             {
                                 RoomID = a.RoomID,
                                 RoomName = a.RoomName,
                                 CategoryRoomID = b.CategoryRoomID,
                                 CategoryRoomName = b.CategoryRoomName,
                                 RoomPrice = a.RoomPrice,
                                 RoomStatus = a.Status
                             };
            return Json(new { data = data_query }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult getCategoryRoom(bool? flag)
        {
            var data_categoryRoom = _dbContext.CategoryRooms.ToList();
            return Json(new { data = data_categoryRoom, status = true }, JsonRequestBehavior.AllowGet);
        }
        

        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Create()
        {
            if (Session != null || (Session)["AdminID"] != null || (Session)["AdminID"].ToString() != "")
            {
                string adminID = Session["AdminID"] as string;
                var dataUser = _dbContext.Admins.Where(x => x.ID == adminID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View();
        }

        

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult Create(string room_name, string category_room, int price_room)
        {
            Room room = new Room
            {
                RoomID = RandomString.getRandomString(5),
                RoomName = room_name.ToString(),
                CategoryRoomID = category_room.ToString(),
                RoomPrice = decimal.Parse(price_room.ToString()),
                Status = false
            };

            var create = _dbContext.Rooms.Add(room);

            if (create != null)
            {
                try
                {
                    _dbContext.SaveChanges();
                    return Json(new { data = "Thêm thành công", status = true }, JsonRequestBehavior.AllowGet);
                }
                catch (DbEntityValidationException e)
                {
                    return Json(new { data = e.Message, status = false }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { data = "Thêm thất bại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Edit(string id)
        {
            if (Session != null || (Session)["AdminID"] != null || (Session)["AdminID"].ToString() != "")
            {
                string adminID = Session["AdminID"] as string;
                var dataUser = _dbContext.Admins.Where(x => x.ID == adminID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            var roomData = _dbContext.Rooms.Where(x => x.RoomID == id).FirstOrDefault();
            ViewBag.roomData = roomData;
            return View();
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult Edit(string room_name, string category_room, decimal price_room, string id)
        {
            var check = _dbContext.Rooms.Where(x => x.RoomID == id).FirstOrDefault();
            if (check != null)
            {
                check.RoomName = room_name;
                check.RoomPrice = price_room;
                check.CategoryRoomID = category_room;
                _dbContext.SaveChanges();

                return Json(new { data = "Cập nhật thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Loại phòng không tồn tại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [AuthorizeAdmin]
        public JsonResult Delete(string id)
        {
            var check = _dbContext.Rooms.Where(x => x.RoomID == id).FirstOrDefault();
            if (check != null)
            {
                _dbContext.Rooms.Remove(check);
                _dbContext.SaveChanges();

                return Json(new { data = "Xoá thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Loại phòng không tồn tại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Detail(String id)
        {
            if (Session != null || (Session)["AdminID"] != null || (Session)["AdminID"].ToString() != "")
            {
                string adminID = Session["AdminID"] as string;
                var dataUser = _dbContext.Admins.Where(x => x.ID == adminID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            var roomData = _dbContext.Rooms.Where(x => x.RoomID == id).FirstOrDefault();
            var orderData = _dbContext.Orders.Where(x => x.RoomID == id).FirstOrDefault();
            ViewBag.roomData = roomData;
            ViewBag.orderData = orderData;
            return View();
        }
    }
}

QLDPKS/Controllers/CategoryRoomController.cs
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Controllers
{
    public class CategoryRoomController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public CategoryRoomController()
        {
            _dbContext = new QLKSDatabaseContext();
        }
        // GET: CategoryRoom
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult getCategoryRoom()
        {
            var listCategoryRoom = _dbContext.CategoryRooms.OrderBy(x => x.NumberOfGuest).ToList();

            return Json(new { data = listCategoryRoom }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult getNumberOfGuest(string id)
        {
            var dataCategoryRoom = _dbContext.CategoryRooms.Where(x => x.CategoryRoomID == id).FirstOrDefault();
            return Json(new { data = dataCategoryRoom }, JsonRequestBehavior.AllowGet);
        }
    }
}

QLDPKS/Controllers/OrderController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Controllers
{
    public class OrderController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public OrderController()
        {
            _dbContext = new QLKSDatabaseContext();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public JsonResult SubmitBook(string fullname, string email, string category_room, string room, DateTime received_date, DateTime checkout_date, int numberofguest)
        {
            decimal price = _dbContext.Rooms.Where(x => x.RoomID == room).FirstOrDefault().RoomPrice;
            if(received_date < DateTime.Now && checkout_date <= DateTime.Now)
            {
                return Json(new { data = "Thời gian không hợp lệ.", status = false }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string customerID = Session["CustomerID"] as string;
                Order order = new Order
                {
                    OrderID = RandomString.getRandomString(5),
                    CustomerID = (customerID != null) ? customerID : RandomString.getRandomString(5),
                    RoomID = room,
                    Email = email,
                    ReceivedDate = received_date,
                    CheckOutDate = checkout_date,
                    NumberGuest = numberofguest,
                    Amount = price,
                    Status = false
                };
                var create = _dbContext.Orders.Add(order);

                if (create != null)
                {
                    _dbContext.SaveChanges();
                    return Json(new { data = "Đặt phòng thành công, vui lòng kiểm tra Mail", status = true }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { data = "Có lỗi xảy ra, vui lòng đợi", status = false }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

QLDPKS/Areas/Admin/Views/Admin/CategoryRoom.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@section categoryRoom {active}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Danh sách loại phòng</h1>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách loại phòng</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" cellspacing="0" role="grid">
                            <thead>
                                <tr role="row">
                                    <th>Tên loại phòng</th>
                                    <th>Số khách</th>
                                    <th>Cập nhật</th>
                                    <th>Xoá</th>
                                </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="my-2"></div>
        <a href="@Url.Action("Create", "CategoryRoom", new { area = "Admin" })" class="btn btn-success btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-check"></i>
            </span>
            <span class="text">Thêm loại phòng mới</span>
        </a>
    </div>
</div>

@section scripts {
    <script>
        "use strict"
        $(document).ready(function () {
            getCategoryRoom()
        })

        function getCategoryRoom() {
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("getCategoryRoom", "CategoryRoom", new { area = "Admin" })",
                    data: { "flag": true },
                    dataType: "json",
                    beforeSend: function () {
                        Swal.fire({
                            text: "Đang lấy dữ liệu ...",
                            timer: 10000,
                            onOpen: () => {
                                swal.showLoading()
                            }
                        })
                    },
                    success: function (response) {
                        let data = ""
                        $.each(response.data, function (i, item) {
                            var editCategoryRoom = '@Url.Action("Edit", "CategoryRoom", new { area = "Admin", id = "_id_" })'.replace('_id_', item.CategoryRoomID)
                            data += "<tr role=\"row\" class=\"odd\">"
                            data += "<td>" + item.CategoryRoomName + "</td>"
                            data += "<td>" + item.NumberOfGuest + "</td>"
                            data += "<td>"
                            data += "<a href=\"" + editCategoryRoom + "\" class=\"btn btn-warning btn-circle btn-sm\">"
                            data += "<i class=\"fas fa-exclamation-triangle\"></i>"
                            data += "</a>"
                            data += "</td>"
                            data += "<td>"
                            data += "<button onclick=\"deleteCategoryRoom('" + item.CategoryRoomID + "')\" class=\"btn btn-danger btn-circle btn-sm\">"
                            data += "<i class=\"fas fa-trash\"></i>"
                            data += "</button>"
                            data += "</td>"
                            data += "</tr>"
                        })
                        $("tbody").append(data)
                        Swal.close()
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr.responseText)
                    }
                })
                return false
        }

        function deleteCategoryRoom(id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("Delete", "CategoryRoom", new { area = "Admin" })",
                data: { "id": id },
                dataType: "json",
                beforeSend: function () {
                    Swal.fire({
                        text: "Đang xoá ...",
                        onOpen: () => {
                            swal.showLoading()
                        }
                    })
                },
                success: function (response) {
                    if (response.status == true) {
                        Swal.fire({
                            position: "center",
                            type: "success",
                            title: response.data,
                            showConfirmButton: false,
                            timer: 1000
                        })
                        .then(function () {
                            window.location.href = "@Url.Action("CategoryRoom", "Admin", new { area = "Admin" })"
                        })
                    }
                    else {
                        Swal.fire({
                            position: "center",
                            type: "error",
                            title: response.data,
                            showConfirmButton: false,
                            timer: 1000
                        })
                    }
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText)
                }
            })
            return false
        }
    </script>
}

QLDPKS/Areas/Admin/Views/Admin/Order.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@section approveOrder {active}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Danh sách đơn chưa duyệt</h1>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Danh sách đơn chưa duyệt</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        <table class="table table-bordered dataTable" id="dataTable" cellspacing="0" role="grid">
                            <thead>
                                <tr role="row">
                                    <th>Người đặt</th>
                                    <th>Tên phòng</th>
                                    <th>Loại phòng</th>
                                    <th>Ngày nhận</th>
                                    <th>Ngày trả</th>
                                    <th>Giá</th>
                                    <th>Trạng thái</th>
                                    <th>Duyệt</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script>
        "use strict"
        $(document).ready(function () {
            getOrder()
        })

        function getOrder() {
            $.ajax({
                    type: "POST",
                    url: "@Url.Action("getOrder", "Order", new { area = "Admin" })",
                    data: { "flag": true },
                    dataType: "json",
                    beforeSend: function () {
                        Swal.fire({
                            text: "Đang lấy dữ liệu ...",
                            timer: 10000,
                            onOpen: () => {
                                swal.showLoading()
                            }
                        })
                    },
                success: function (response) {
                        let data = ""
                    $.each(response.data, function (i, item) {
                        let ReceivedDate = new Date(parseInt(item.ReceivedDate.replace(/\/Date\((-?\d+)\)\//, '$1')));
                        let CheckOutDate = new Date(parseInt(item.CheckOutDate.replace(/\/Date\((-?\d+)\)\//, '$1')));
                        data += "<tr role=\"row\" class=\"odd\">"
                        data += "<td>" + item.Email + "</td>"
                        data += "<td>" + item.RoomName + "</td>"
                        data += "<td>" + item.CategoryRoomName + "</td>"
                        data += "<td>" + ReceivedDate + "</td>"
                        data += "<td>" + CheckOutDate + "</td>"
                        data += "<td>" + item.Amount + "</td>"
                        data += "<td>" + item.Status + "</td>"
                        data += "<td>"
                        data += "<button onclick=\"approveOrder('" + item.OrderID + "')\" class=\"btn btn-success btn-circle btn-sm\">"
                        data += "<i class=\"fas fa-check\"></i>"
                        data += "</button>"
                        data += "</td>"
                        data += "</tr>"
                    })

                    $("tbody").append(data)
                    Swal.close()
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText)
                }
            })
            return false
        }

        function approveOrder(id) {
            $.ajax({
                type: "POST",
                url: "@Url.Action("approveOrder", "Order", new { area = "Admin" })",
                data: { "id": id },
                dataType: "json",
                beforeSend: function () {
                    Swal.fire({
                        text: "Đang duyệt đơn ...",
                        onOpen: () => {
                            swal.showLoading()
                        }
                    })
                },
                success: function (response) {
                    if (response.status == true) {
                        Swal.fire({
                            position: "center",
                            type: "success",
                            title: response.data,
                            showConfirmButton: false,
                            timer: 1000
                        })
                        .then(function () {
                            window.location.href = "@Url.Action("Order", "Admin", new { area = "Admin" })"
                        })
                    }
                    else {
                        Swal.fire({
                            position: "center",
                            type: "error",
                            title: response.data,
                            showConfirmButton: false,
                            timer: 1000
                        })
                    }
                },
                error: function (xhr, status, error) {
                    console.log(xhr.responseText)
                }
            })
            return false
        }
    </script>
}