QLDPKS/Areas/Admin/Controllers/HomeController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public HomeController()
        {
            _dbContext = new QLKSDatabaseContext();
        }
        [HttpGet]
        [AuthorizeAdmin]
        public ActionResult Index()
        {
            if (Session != null || (Session)["Admin"] != null || (Session)["AdminID"].ToString() != "")
            {
                string adminID = Session["AdminID"] as string;
                var dataUser = _dbContext.Admins.Where(x => x.ID == adminID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Login", "Account", new { area = "Admin" });
            }

            return View();
        }
    }
}

QLDPKS/Areas/Customer/Controllers/CustomerController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Areas.Customer.Controllers
{
    public class CustomerController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public CustomerController()
        {
            _dbContext = new QLKSDatabaseContext();
        }

        [HttpPost]
        [AuthorizeAccount]
        public JsonResult UpdateCustomer(string address, string cellphone)
        {
            string customerID = (string)Session["CustomerID"];
            var updateCustomer = _dbContext.Customers.Where(x => x.CustomerID == customerID).FirstOrDefault();

            if(updateCustomer != null)
            {
                updateCustomer.CustomerAddress = address;
                updateCustomer.CustomerCellphone = cellphone;

                _dbContext.SaveChanges();
                return Json(new { data = "Cập nhật thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Cập nhật thất bại", status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [AuthorizeAccount]
        public ActionResult ChangePassword()
        {
            if (Session != null || (Session)["CustomerID"] != null || (Session)["CustomerID"].ToString() != "")
            {
                string customerID = Session["CustomerID"] as string;
                var dataUser = _dbContext.Customers.Where(x => x.CustomerID == customerID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View();
        }

        [HttpPost]
        [AuthorizeAccount]
        public JsonResult ChangePassword(string old_password, string new_password)
        {
            string hash_password = StringHash.crypto(old_password);
            string customerID = (string)Session["CustomerID"];
            var updatePasswordCustomer = _dbContext.Customers.Where(x => x.CustomerID == customerID && x.CustomerPassword == hash_password).FirstOrDefault();

            if(updatePasswordCustomer != null)
            {
                string hash_new_password = StringHash.crypto(new_password);
                updatePasswordCustomer.CustomerPassword = hash_new_password;
                _dbContext.SaveChanges();

                return Json(new { data = "Đổi mật khẩu thành công", status = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Mật khẩu cũ không chính xác", status = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        [AuthorizeAccount]
        public ActionResult Order()
        {
            if (Session != null || (Session)["CustomerID"] != null || (Session)["CustomerID"].ToString() != "")
            {
                string customerID = Session["CustomerID"] as string;
                var dataUser = _dbContext.Customers.Where(x => x.CustomerID == customerID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View();
        }

        [HttpPost]
        [AuthorizeAccount]
        public JsonResult Order(bool? flag)
        {
            string customerID = Session["CustomerID"] as string;

            var dataOrder = from a in _dbContext.Customers
                            join b in _dbContext.Orders
                            on a.CustomerID equals b.CustomerID
                            join c in _dbContext.Rooms
                            on b.RoomID equals c.RoomID
                            join d in _dbContext.CategoryRooms
                            on c.CategoryRoomID equals d.CategoryRoomID
                            where a.CustomerID == customerID
                            select new
                            {
                                CustomerName = a.CustomerName,
                                RoomName = c.RoomName,
                                CategoryRoomName = d.CategoryRoomName,
                                ReceivedDate = b.ReceivedDate,
                                CheckOutDate = b.CheckOutDate,
                                NumberOfGuest = b.NumberGuest,
                                Amount = b.Amount,
                                Status = b.Status
                            };

            return Json(new { data = dataOrder }, JsonRequestBehavior.AllowGet);
        }
    }
}

QLDPKS/Areas/Customer/Controllers/HomeController.cs
using QLDPKS.Cores;
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Areas.Customer.Controllers
{
    public class HomeController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public HomeController()
        {
            _dbContext = new QLKSDatabaseContext();
        }
        [HttpGet]
        [AuthorizeAccount]
        public ActionResult Index()
        {
            if (Session != null || (Session)["CustomerID"] != null || (Session)["CustomerID"].ToString() != "")
            {
                string customerID = Session["CustomerID"] as string;
                var dataUser = _dbContext.Customers.Where(x => x.CustomerID == customerID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View();
        }
    }
}

QLDPKS/Controllers/HomeController.cs
using QLDPKS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLDPKS.Controllers
{
    public class HomeController : Controller
    {
        private readonly QLKSDatabaseContext _dbContext;

        public HomeController()
        {
            _dbContext = new QLKSDatabaseContext();
        }
        [HttpGet]
        public ActionResult Index()
        {
            if(Session != null || (Session)["CustomerID"] != null || (Session)["CustomerID"].ToString() != "")
            {
                string customerID = Session["CustomerID"] as string;
                var dataUser = _dbContext.Customers.Where(x => x.CustomerID == customerID).FirstOrDefault();
                ViewBag.dataUser = dataUser;
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

QLDPKS/Areas/Customer/Views/Home/Index.cshtml
@{
    Layout = "~/Areas/Customer/Views/Shared/_Layouts.cshtml";
}

@section info_user {active}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Thông tin cá nhân</h1>
</div>
<div class="row">
    <div class="col-lg-12 mb-4">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Thay đổi thông tin</h6>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Tên đăng nhập</label>
                    <input type="text" class="form-control form-control-user" id="username" name="username" placeholder="Nhập tên đăng nhập" disabled value="@ViewBag.dataUser.CustomerName">
                </div>
                <div class="form-group">
                    <label>Mật khẩu</label>
                    <input type="password" class="form-control form-control-user" id="password" name="password" placeholder="Nhập mật khẩu" disabled value="@ViewBag.dataUser.CustomerPassword">
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control form-control-user" id="email" name="email" placeholder="Nhập Email" value="@ViewBag.dataUser.CustomerEmail" disabled>
                </div>
                <div class="form-group">
                    <label>Địa chỉ</label>
                    <input type="text" class="form-control form-control-user" id="address" name="address" placeholder="Nhập địa chỉ" value="@ViewBag.dataUser.CustomerAddress">
                </div>
                <div class="form-group">
                    <label>Số địa thoại</label>
                    <input type="number" class="form-control form-control-user" id="cellphone" name="cellphone" placeholder="Nhập số điện thoại" value="@ViewBag.dataUser.CustomerCellphone">
                </div>
                <button id="update" class="btn btn-primary btn-user btn-block">
                    Cập nhật
                </button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        "use strict"
        $(document).ready(function () {
            $('#update').on('click', function () {
                submitUpdate()
            })
        })

        function submitUpdate() {
            let inputAddress = $("input[id=\"address\"]").val()
            let inputCellphone = $("input[id=\"cellphone\"]").val()

            if (typeof inputAddress === "undefined" || inputAddress == null || inputAddress == "") {
                Swal.fire({
                    position: "center",
                    type: "error",
                    title: "Địa chỉ không được để trống",
                    showConfirmButton: false,
                    timer: 1000
                })
                return false
            }
            else if (typeof inputCellphone === "undefined" || inputCellphone == null || inputCellphone == "") {
                Swal.fire({
                    position: "center",
                    type: "error",
                    title: "Số điện thoại không được để trống",
                    showConfirmButton: false,
                    timer: 1000
                })
                return false
            }
            else {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("UpdateCustomer", "Customer", new { area = "Customer" })",
                    data: { "address": inputAddress, "cellphone": inputCellphone },
                    dataType: "json",
                    beforeSend: function () {
                        Swal.fire({
                            text: "Đang cập nhật ...",
                            onOpen: () => {
                                swal.showLoading()
                            }
                        })
                    },
                    success: function (response) {
                        if (response.status == true) {
                            Swal.fire({
                                position: "center",
                                type: "success",
                                title: response.data,
                                showConfirmButton: false,
                                timer: 1000
                            })
                                .then(function () {
                                    window.location.href = "@Url.Action("Index", "Home", new { area = "Customer" })"
                                })
                        }
                        else {
                            Swal.fire({
                                position: "center",
                                type: "error",
                                title: response.data,
                                showConfirmButton: false,
                                timer: 1000
                            })
                        }
                    },
                    error: function (xhr, status, error) {
                        console.log(xhr.responseText)
                    }
                })
                return false
            }
        }
    </script>
}